version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "64064:64064"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD_H2}
      SERVER_PORT: 64064
      API_SECRET_SECURITY_SECRET: ${JWT_SECRET}
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_H2}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
